mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',include('posts.urls')),
    path('auth/', include("users.urls"))
]

mysite/posts/urls.py
# from django.urls import path
# from . import views

# urlpatterns = [
#     path("home", views.home_view)
# ]

mysite/users/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("login", views.login_view, name='login'), # *name을 주면 템플릿에서 간단하게 사용 가능
    path("logout", views.logout_view, name="logout"),
    path("signup", views.signup_view, name="signup")
]

mysite/posts/models.py
from django.db import models

# Create your models here.

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser): # 유저
    student_id = models.CharField(max_length=10) # 학번

mysite/posts/views.py
from django.shortcuts import render

# Create your views here.

# def home_view(request):
#     return render(request, "home/home.html") # 해당 위치

mysite/users/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from .models import User
# Create your views here.

def login_view(request):
    if request.method == "POST": # 만약에 POST라면
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        if user is not None:
            print("로그인 성공") # admin/1 -> 로그인 성공
            login(request, user) # -> 로그인된 상태(보여줄 수 있는것 만들기)
        else:
            print("로그인 실패") # 그 외 -> 로그인 실패

        # 참고 : https://docs.djangoproject.com/en/4.0/topics/auth/default/#django.contrib.auth.authenticate
    return render(request, "users/login.html") # 해당 위치

def logout_view(request):
    logout(request)
    return redirect("user:login") # 로그아웃이 끝났을 때는 로그인 페이지로

def signup_view(request): # 회원가입

    if request.method == "POST":
        print(request.POST) # POST라면 확인
        username = request.POST["username"] # 입력한 값 확인
        password = request.POST["password"]
        firstname = request.POST["firstname"]
        lastname = request.POST["lastname"]
        email = request.POST["email"]
        student_id = request.POST["student_id"]

        user = User.objects.create_user(username, email, password) # 유저, 이메일, 비밀번호

        user.last_name = lastname # 추가적인 정보
        user.first_name = firstname
        user.student_id = student_id
        user.save()
        return redirect("user:login") # 회원가입을 하였으니 로그인하여라

    return render(request, "users/signup.html")

mysite/posts/templates/home/home.html
홈 화면

mysite/users/templates/users/login.html
로그인 페이지

<br>
{% if user.is_authenticated %} <!-- 로그인 성공 -->
    로그인 성공!
    {{ user.username }}님 환영합니다.
    <a href="{% url 'user:logout' %}">로그아웃</a>
{% else %} <!-- 로그인 실패 -->

<form action="" method="POST">
    {% csrf_token%}
    <input name="username" type="text">
    <input name="password" type="password">
    <input type="submit" value="로그인">
</form>
<a href="{% url 'user:signup' %}">회원가입</a>
{% endif %}

mysite/users/templates/users/signup.html
회원가입 페이지
<br>

<form action="" method="POST">
    {% csrf_token %} 
    <p>아이디</p>
    <input name="username" type="text"> <!-- id -->
    <p>비밀번호</p>
    <input name="password" type="password"> <!-- password -->
    <p>성</p>
    <input name="firstname" type="text"> <!-- 성 -->
    <p>이름</p>
    <input name="lastname" type="text"> <!-- 이름 -->
    <p>이메일</p>
    <input name="email" type="text"> <!-- 이메일 -->
    <p>학번</p>
    <input name="student_id" type="text"> <!-- 모델의 student_id --> 
    <input type="submit" value="회원가입"> <!-- 제출 버튼 -->

</form>